/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BreakfastStAlbansRouteImport } from './routes/breakfast-st-albans'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CourtStaffRouteImport } from './routes/court-staff'
import { Route as DisplayRouteImport } from './routes/display'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as GooglePayReviewRouteImport } from './routes/google-pay-review'
import { Route as GooglePayTestRouteImport } from './routes/google-pay-test'
import { Route as HalalFoodStAlbansRouteImport } from './routes/halal-food-st-albans'
import { Route as JudgesRouteImport } from './routes/judges'
import { Route as JudgesMenuRouteImport } from './routes/judges-menu'
import { Route as JurorRouteImport } from './routes/juror'
import { Route as JurorDemoRouteImport } from './routes/juror-demo'
import { Route as JurorQrRouteImport } from './routes/juror-qr'
import { Route as JuryMenuRouteImport } from './routes/jury-menu'
import { Route as KdsRouteImport } from './routes/kds'
import { Route as LandlordRouteImport } from './routes/landlord'
import { Route as LunchStAlbansRouteImport } from './routes/lunch-st-albans'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OrderDirectRouteImport } from './routes/order-direct'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as TabRouteImport } from './routes/tab'
import { Route as TeamLoginRouteImport } from './routes/team-login'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TillRouteImport } from './routes/till'
import { Route as WatcherDownloadRouteImport } from './routes/watcher-download'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAccountsRouteImport } from './routes/admin.accounts'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminBroadcastsRouteImport } from './routes/admin.broadcasts'
import { Route as AdminCourtStaffRouteImport } from './routes/admin.court-staff'
import { Route as AdminCustomerDiscountsRouteImport } from './routes/admin.customer-discounts'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminJurorAttendanceRouteImport } from './routes/admin.juror-attendance'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminOperationsRouteImport } from './routes/admin.operations'
import { Route as AdminPosRouteImport } from './routes/admin.pos'
import { Route as AdminPromosRouteImport } from './routes/admin.promos'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStaffOpsRouteImport } from './routes/admin.staff-ops'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVouchersRouteImport } from './routes/admin.vouchers'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as OrderOrderIdRouteImport } from './routes/order.$orderId'
import { Route as PayOrderIdRouteImport } from './routes/pay.$orderId'
import { Route as PrintOrderIdRouteImport } from './routes/print.$orderId'
import { Route as ApiPublicCleanupUnpaidRouteImport } from './routes/api/public/cleanup-unpaid'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicJurorDailyRouteImport } from './routes/api/public/juror-daily'
import { Route as ApiPublicSumupReaderWebhookRouteImport } from './routes/api/public/sumup-reader-webhook'
import { Route as ApiPublicSumupWebhookRouteImport } from './routes/api/public/sumup-webhook'
import { Route as ApiPublicDeliverooHubIngestRouteImport } from './routes/api/public/deliveroo/hub-ingest'
import { Route as ApiPublicDeliverooPrintBridgeRouteImport } from './routes/api/public/deliveroo/print-bridge'
import { Route as ApiPublicDeliverooWebhookRouteImport } from './routes/api/public/deliveroo/webhook'
import { Route as ApiPublicJusteatHubIngestRouteImport } from './routes/api/public/justeat/hub-ingest'
import { Route as ApiPublicJusteatWebhookRouteImport } from './routes/api/public/justeat/webhook'
import { Route as ApiPublicLandlordReportRouteImport } from './routes/api/public/landlord/report'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BreakfastStAlbansRoute = BreakfastStAlbansRouteImport.update({
  id: '/breakfast-st-albans',
  path: '/breakfast-st-albans',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CourtStaffRoute = CourtStaffRouteImport.update({
  id: '/court-staff',
  path: '/court-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayRoute = DisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const GooglePayReviewRoute = GooglePayReviewRouteImport.update({
  id: '/google-pay-review',
  path: '/google-pay-review',
  getParentRoute: () => rootRouteImport,
} as any)
const GooglePayTestRoute = GooglePayTestRouteImport.update({
  id: '/google-pay-test',
  path: '/google-pay-test',
  getParentRoute: () => rootRouteImport,
} as any)
const HalalFoodStAlbansRoute = HalalFoodStAlbansRouteImport.update({
  id: '/halal-food-st-albans',
  path: '/halal-food-st-albans',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgesRoute = JudgesRouteImport.update({
  id: '/judges',
  path: '/judges',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgesMenuRoute = JudgesMenuRouteImport.update({
  id: '/judges-menu',
  path: '/judges-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const JurorRoute = JurorRouteImport.update({
  id: '/juror',
  path: '/juror',
  getParentRoute: () => rootRouteImport,
} as any)
const JurorDemoRoute = JurorDemoRouteImport.update({
  id: '/juror-demo',
  path: '/juror-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const JurorQrRoute = JurorQrRouteImport.update({
  id: '/juror-qr',
  path: '/juror-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const JuryMenuRoute = JuryMenuRouteImport.update({
  id: '/jury-menu',
  path: '/jury-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const KdsRoute = KdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordRoute = LandlordRouteImport.update({
  id: '/landlord',
  path: '/landlord',
  getParentRoute: () => rootRouteImport,
} as any)
const LunchStAlbansRoute = LunchStAlbansRouteImport.update({
  id: '/lunch-st-albans',
  path: '/lunch-st-albans',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderDirectRoute = OrderDirectRouteImport.update({
  id: '/order-direct',
  path: '/order-direct',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const TabRoute = TabRouteImport.update({
  id: '/tab',
  path: '/tab',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamLoginRoute = TeamLoginRouteImport.update({
  id: '/team-login',
  path: '/team-login',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TillRoute = TillRouteImport.update({
  id: '/till',
  path: '/till',
  getParentRoute: () => rootRouteImport,
} as any)
const WatcherDownloadRoute = WatcherDownloadRouteImport.update({
  id: '/watcher-download',
  path: '/watcher-download',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/admin/accounts',
  path: '/admin/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/admin/banners',
  path: '/admin/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBroadcastsRoute = AdminBroadcastsRouteImport.update({
  id: '/admin/broadcasts',
  path: '/admin/broadcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCourtStaffRoute = AdminCourtStaffRouteImport.update({
  id: '/admin/court-staff',
  path: '/admin/court-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomerDiscountsRoute = AdminCustomerDiscountsRouteImport.update({
  id: '/admin/customer-discounts',
  path: '/admin/customer-discounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/admin/inventory',
  path: '/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJurorAttendanceRoute = AdminJurorAttendanceRouteImport.update({
  id: '/admin/juror-attendance',
  path: '/admin/juror-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/admin/locations',
  path: '/admin/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/admin/menu',
  path: '/admin/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOperationsRoute = AdminOperationsRouteImport.update({
  id: '/admin/operations',
  path: '/admin/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPosRoute = AdminPosRouteImport.update({
  id: '/admin/pos',
  path: '/admin/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPromosRoute = AdminPromosRouteImport.update({
  id: '/admin/promos',
  path: '/admin/promos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/admin/security',
  path: '/admin/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffOpsRoute = AdminStaffOpsRouteImport.update({
  id: '/admin/staff-ops',
  path: '/admin/staff-ops',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVouchersRoute = AdminVouchersRouteImport.update({
  id: '/admin/vouchers',
  path: '/admin/vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderIdRoute = OrderOrderIdRouteImport.update({
  id: '/order/$orderId',
  path: '/order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const PayOrderIdRoute = PayOrderIdRouteImport.update({
  id: '/pay/$orderId',
  path: '/pay/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintOrderIdRoute = PrintOrderIdRouteImport.update({
  id: '/print/$orderId',
  path: '/print/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCleanupUnpaidRoute = ApiPublicCleanupUnpaidRouteImport.update({
  id: '/api/public/cleanup-unpaid',
  path: '/api/public/cleanup-unpaid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJurorDailyRoute = ApiPublicJurorDailyRouteImport.update({
  id: '/api/public/juror-daily',
  path: '/api/public/juror-daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSumupReaderWebhookRoute =
  ApiPublicSumupReaderWebhookRouteImport.update({
    id: '/api/public/sumup-reader-webhook',
    path: '/api/public/sumup-reader-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSumupWebhookRoute = ApiPublicSumupWebhookRouteImport.update({
  id: '/api/public/sumup-webhook',
  path: '/api/public/sumup-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeliverooHubIngestRoute =
  ApiPublicDeliverooHubIngestRouteImport.update({
    id: '/api/public/deliveroo/hub-ingest',
    path: '/api/public/deliveroo/hub-ingest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDeliverooPrintBridgeRoute =
  ApiPublicDeliverooPrintBridgeRouteImport.update({
    id: '/api/public/deliveroo/print-bridge',
    path: '/api/public/deliveroo/print-bridge',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDeliverooWebhookRoute =
  ApiPublicDeliverooWebhookRouteImport.update({
    id: '/api/public/deliveroo/webhook',
    path: '/api/public/deliveroo/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJusteatHubIngestRoute =
  ApiPublicJusteatHubIngestRouteImport.update({
    id: '/api/public/justeat/hub-ingest',
    path: '/api/public/justeat/hub-ingest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicJusteatWebhookRoute = ApiPublicJusteatWebhookRouteImport.update({
  id: '/api/public/justeat/webhook',
  path: '/api/public/justeat/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLandlordReportRoute = ApiPublicLandlordReportRouteImport.update({
  id: '/api/public/landlord/report',
  path: '/api/public/landlord/report',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/breakfast-st-albans': typeof BreakfastStAlbansRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/complaints': typeof ComplaintsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/court-staff': typeof CourtStaffRoute
  '/display': typeof DisplayRoute
  '/driver': typeof DriverRoute
  '/faq': typeof FaqRoute
  '/gdpr': typeof GdprRoute
  '/google-pay-review': typeof GooglePayReviewRoute
  '/google-pay-test': typeof GooglePayTestRoute
  '/halal-food-st-albans': typeof HalalFoodStAlbansRoute
  '/judges': typeof JudgesRoute
  '/judges-menu': typeof JudgesMenuRoute
  '/juror': typeof JurorRoute
  '/juror-demo': typeof JurorDemoRoute
  '/juror-qr': typeof JurorQrRoute
  '/jury-menu': typeof JuryMenuRoute
  '/kds': typeof KdsRoute
  '/landlord': typeof LandlordRoute
  '/lunch-st-albans': typeof LunchStAlbansRoute
  '/menu': typeof MenuRoute
  '/order-direct': typeof OrderDirectRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRoute
  '/tab': typeof TabRoute
  '/team-login': typeof TeamLoginRoute
  '/terms': typeof TermsRoute
  '/till': typeof TillRoute
  '/watcher-download': typeof WatcherDownloadRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/court-staff': typeof AdminCourtStaffRoute
  '/admin/customer-discounts': typeof AdminCustomerDiscountsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/juror-attendance': typeof AdminJurorAttendanceRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff-ops': typeof AdminStaffOpsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/print/$orderId': typeof PrintOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/cleanup-unpaid': typeof ApiPublicCleanupUnpaidRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/juror-daily': typeof ApiPublicJurorDailyRoute
  '/api/public/sumup-reader-webhook': typeof ApiPublicSumupReaderWebhookRoute
  '/api/public/sumup-webhook': typeof ApiPublicSumupWebhookRoute
  '/api/public/deliveroo/hub-ingest': typeof ApiPublicDeliverooHubIngestRoute
  '/api/public/deliveroo/print-bridge': typeof ApiPublicDeliverooPrintBridgeRoute
  '/api/public/deliveroo/webhook': typeof ApiPublicDeliverooWebhookRoute
  '/api/public/justeat/hub-ingest': typeof ApiPublicJusteatHubIngestRoute
  '/api/public/justeat/webhook': typeof ApiPublicJusteatWebhookRoute
  '/api/public/landlord/report': typeof ApiPublicLandlordReportRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/breakfast-st-albans': typeof BreakfastStAlbansRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/complaints': typeof ComplaintsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/court-staff': typeof CourtStaffRoute
  '/display': typeof DisplayRoute
  '/driver': typeof DriverRoute
  '/faq': typeof FaqRoute
  '/gdpr': typeof GdprRoute
  '/google-pay-review': typeof GooglePayReviewRoute
  '/google-pay-test': typeof GooglePayTestRoute
  '/halal-food-st-albans': typeof HalalFoodStAlbansRoute
  '/judges': typeof JudgesRoute
  '/judges-menu': typeof JudgesMenuRoute
  '/juror': typeof JurorRoute
  '/juror-demo': typeof JurorDemoRoute
  '/juror-qr': typeof JurorQrRoute
  '/jury-menu': typeof JuryMenuRoute
  '/kds': typeof KdsRoute
  '/landlord': typeof LandlordRoute
  '/lunch-st-albans': typeof LunchStAlbansRoute
  '/menu': typeof MenuRoute
  '/order-direct': typeof OrderDirectRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRoute
  '/tab': typeof TabRoute
  '/team-login': typeof TeamLoginRoute
  '/terms': typeof TermsRoute
  '/till': typeof TillRoute
  '/watcher-download': typeof WatcherDownloadRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/court-staff': typeof AdminCourtStaffRoute
  '/admin/customer-discounts': typeof AdminCustomerDiscountsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/juror-attendance': typeof AdminJurorAttendanceRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff-ops': typeof AdminStaffOpsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/print/$orderId': typeof PrintOrderIdRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/api/public/cleanup-unpaid': typeof ApiPublicCleanupUnpaidRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/juror-daily': typeof ApiPublicJurorDailyRoute
  '/api/public/sumup-reader-webhook': typeof ApiPublicSumupReaderWebhookRoute
  '/api/public/sumup-webhook': typeof ApiPublicSumupWebhookRoute
  '/api/public/deliveroo/hub-ingest': typeof ApiPublicDeliverooHubIngestRoute
  '/api/public/deliveroo/print-bridge': typeof ApiPublicDeliverooPrintBridgeRoute
  '/api/public/deliveroo/webhook': typeof ApiPublicDeliverooWebhookRoute
  '/api/public/justeat/hub-ingest': typeof ApiPublicJusteatHubIngestRoute
  '/api/public/justeat/webhook': typeof ApiPublicJusteatWebhookRoute
  '/api/public/landlord/report': typeof ApiPublicLandlordReportRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/breakfast-st-albans': typeof BreakfastStAlbansRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/complaints': typeof ComplaintsRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/court-staff': typeof CourtStaffRoute
  '/display': typeof DisplayRoute
  '/driver': typeof DriverRoute
  '/faq': typeof FaqRoute
  '/gdpr': typeof GdprRoute
  '/google-pay-review': typeof GooglePayReviewRoute
  '/google-pay-test': typeof GooglePayTestRoute
  '/halal-food-st-albans': typeof HalalFoodStAlbansRoute
  '/judges': typeof JudgesRoute
  '/judges-menu': typeof JudgesMenuRoute
  '/juror': typeof JurorRoute
  '/juror-demo': typeof JurorDemoRoute
  '/juror-qr': typeof JurorQrRoute
  '/jury-menu': typeof JuryMenuRoute
  '/kds': typeof KdsRoute
  '/landlord': typeof LandlordRoute
  '/lunch-st-albans': typeof LunchStAlbansRoute
  '/menu': typeof MenuRoute
  '/order-direct': typeof OrderDirectRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRoute
  '/tab': typeof TabRoute
  '/team-login': typeof TeamLoginRoute
  '/terms': typeof TermsRoute
  '/till': typeof TillRoute
  '/watcher-download': typeof WatcherDownloadRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/court-staff': typeof AdminCourtStaffRoute
  '/admin/customer-discounts': typeof AdminCustomerDiscountsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/juror-attendance': typeof AdminJurorAttendanceRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff-ops': typeof AdminStaffOpsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vouchers': typeof AdminVouchersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/order/$orderId': typeof OrderOrderIdRoute
  '/pay/$orderId': typeof PayOrderIdRoute
  '/print/$orderId': typeof PrintOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/cleanup-unpaid': typeof ApiPublicCleanupUnpaidRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/juror-daily': typeof ApiPublicJurorDailyRoute
  '/api/public/sumup-reader-webhook': typeof ApiPublicSumupReaderWebhookRoute
  '/api/public/sumup-webhook': typeof ApiPublicSumupWebhookRoute
  '/api/public/deliveroo/hub-ingest': typeof ApiPublicDeliverooHubIngestRoute
  '/api/public/deliveroo/print-bridge': typeof ApiPublicDeliverooPrintBridgeRoute
  '/api/public/deliveroo/webhook': typeof ApiPublicDeliverooWebhookRoute
  '/api/public/justeat/hub-ingest': typeof ApiPublicJusteatHubIngestRoute
  '/api/public/justeat/webhook': typeof ApiPublicJusteatWebhookRoute
  '/api/public/landlord/report': typeof ApiPublicLandlordReportRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/breakfast-st-albans'
    | '/cart'
    | '/checkout'
    | '/complaints'
    | '/contact'
    | '/cookies'
    | '/court-staff'
    | '/display'
    | '/driver'
    | '/faq'
    | '/gdpr'
    | '/google-pay-review'
    | '/google-pay-test'
    | '/halal-food-st-albans'
    | '/judges'
    | '/judges-menu'
    | '/juror'
    | '/juror-demo'
    | '/juror-qr'
    | '/jury-menu'
    | '/kds'
    | '/landlord'
    | '/lunch-st-albans'
    | '/menu'
    | '/order-direct'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/staff'
    | '/tab'
    | '/team-login'
    | '/terms'
    | '/till'
    | '/watcher-download'
    | '/admin/accounts'
    | '/admin/banners'
    | '/admin/blog'
    | '/admin/broadcasts'
    | '/admin/court-staff'
    | '/admin/customer-discounts'
    | '/admin/inventory'
    | '/admin/juror-attendance'
    | '/admin/locations'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/operations'
    | '/admin/pos'
    | '/admin/promos'
    | '/admin/reports'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/staff-ops'
    | '/admin/users'
    | '/admin/vouchers'
    | '/blog/$slug'
    | '/order/$orderId'
    | '/pay/$orderId'
    | '/print/$orderId'
    | '/admin/'
    | '/blog/'
    | '/api/public/cleanup-unpaid'
    | '/api/public/health'
    | '/api/public/juror-daily'
    | '/api/public/sumup-reader-webhook'
    | '/api/public/sumup-webhook'
    | '/api/public/deliveroo/hub-ingest'
    | '/api/public/deliveroo/print-bridge'
    | '/api/public/deliveroo/webhook'
    | '/api/public/justeat/hub-ingest'
    | '/api/public/justeat/webhook'
    | '/api/public/landlord/report'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/breakfast-st-albans'
    | '/cart'
    | '/checkout'
    | '/complaints'
    | '/contact'
    | '/cookies'
    | '/court-staff'
    | '/display'
    | '/driver'
    | '/faq'
    | '/gdpr'
    | '/google-pay-review'
    | '/google-pay-test'
    | '/halal-food-st-albans'
    | '/judges'
    | '/judges-menu'
    | '/juror'
    | '/juror-demo'
    | '/juror-qr'
    | '/jury-menu'
    | '/kds'
    | '/landlord'
    | '/lunch-st-albans'
    | '/menu'
    | '/order-direct'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/staff'
    | '/tab'
    | '/team-login'
    | '/terms'
    | '/till'
    | '/watcher-download'
    | '/admin/accounts'
    | '/admin/banners'
    | '/admin/blog'
    | '/admin/broadcasts'
    | '/admin/court-staff'
    | '/admin/customer-discounts'
    | '/admin/inventory'
    | '/admin/juror-attendance'
    | '/admin/locations'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/operations'
    | '/admin/pos'
    | '/admin/promos'
    | '/admin/reports'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/staff-ops'
    | '/admin/users'
    | '/admin/vouchers'
    | '/blog/$slug'
    | '/order/$orderId'
    | '/pay/$orderId'
    | '/print/$orderId'
    | '/admin'
    | '/blog'
    | '/api/public/cleanup-unpaid'
    | '/api/public/health'
    | '/api/public/juror-daily'
    | '/api/public/sumup-reader-webhook'
    | '/api/public/sumup-webhook'
    | '/api/public/deliveroo/hub-ingest'
    | '/api/public/deliveroo/print-bridge'
    | '/api/public/deliveroo/webhook'
    | '/api/public/justeat/hub-ingest'
    | '/api/public/justeat/webhook'
    | '/api/public/landlord/report'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/breakfast-st-albans'
    | '/cart'
    | '/checkout'
    | '/complaints'
    | '/contact'
    | '/cookies'
    | '/court-staff'
    | '/display'
    | '/driver'
    | '/faq'
    | '/gdpr'
    | '/google-pay-review'
    | '/google-pay-test'
    | '/halal-food-st-albans'
    | '/judges'
    | '/judges-menu'
    | '/juror'
    | '/juror-demo'
    | '/juror-qr'
    | '/jury-menu'
    | '/kds'
    | '/landlord'
    | '/lunch-st-albans'
    | '/menu'
    | '/order-direct'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/staff'
    | '/tab'
    | '/team-login'
    | '/terms'
    | '/till'
    | '/watcher-download'
    | '/admin/accounts'
    | '/admin/banners'
    | '/admin/blog'
    | '/admin/broadcasts'
    | '/admin/court-staff'
    | '/admin/customer-discounts'
    | '/admin/inventory'
    | '/admin/juror-attendance'
    | '/admin/locations'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/operations'
    | '/admin/pos'
    | '/admin/promos'
    | '/admin/reports'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/staff-ops'
    | '/admin/users'
    | '/admin/vouchers'
    | '/blog/$slug'
    | '/order/$orderId'
    | '/pay/$orderId'
    | '/print/$orderId'
    | '/admin/'
    | '/blog/'
    | '/api/public/cleanup-unpaid'
    | '/api/public/health'
    | '/api/public/juror-daily'
    | '/api/public/sumup-reader-webhook'
    | '/api/public/sumup-webhook'
    | '/api/public/deliveroo/hub-ingest'
    | '/api/public/deliveroo/print-bridge'
    | '/api/public/deliveroo/webhook'
    | '/api/public/justeat/hub-ingest'
    | '/api/public/justeat/webhook'
    | '/api/public/landlord/report'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  BreakfastStAlbansRoute: typeof BreakfastStAlbansRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ComplaintsRoute: typeof ComplaintsRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  CourtStaffRoute: typeof CourtStaffRoute
  DisplayRoute: typeof DisplayRoute
  DriverRoute: typeof DriverRoute
  FaqRoute: typeof FaqRoute
  GdprRoute: typeof GdprRoute
  GooglePayReviewRoute: typeof GooglePayReviewRoute
  GooglePayTestRoute: typeof GooglePayTestRoute
  HalalFoodStAlbansRoute: typeof HalalFoodStAlbansRoute
  JudgesRoute: typeof JudgesRoute
  JudgesMenuRoute: typeof JudgesMenuRoute
  JurorRoute: typeof JurorRoute
  JurorDemoRoute: typeof JurorDemoRoute
  JurorQrRoute: typeof JurorQrRoute
  JuryMenuRoute: typeof JuryMenuRoute
  KdsRoute: typeof KdsRoute
  LandlordRoute: typeof LandlordRoute
  LunchStAlbansRoute: typeof LunchStAlbansRoute
  MenuRoute: typeof MenuRoute
  OrderDirectRoute: typeof OrderDirectRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StaffRoute: typeof StaffRoute
  TabRoute: typeof TabRoute
  TeamLoginRoute: typeof TeamLoginRoute
  TermsRoute: typeof TermsRoute
  TillRoute: typeof TillRoute
  WatcherDownloadRoute: typeof WatcherDownloadRoute
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminBroadcastsRoute: typeof AdminBroadcastsRoute
  AdminCourtStaffRoute: typeof AdminCourtStaffRoute
  AdminCustomerDiscountsRoute: typeof AdminCustomerDiscountsRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminJurorAttendanceRoute: typeof AdminJurorAttendanceRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminOperationsRoute: typeof AdminOperationsRoute
  AdminPosRoute: typeof AdminPosRoute
  AdminPromosRoute: typeof AdminPromosRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffOpsRoute: typeof AdminStaffOpsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVouchersRoute: typeof AdminVouchersRoute
  BlogSlugRoute: typeof BlogSlugRoute
  OrderOrderIdRoute: typeof OrderOrderIdRoute
  PayOrderIdRoute: typeof PayOrderIdRoute
  PrintOrderIdRoute: typeof PrintOrderIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicCleanupUnpaidRoute: typeof ApiPublicCleanupUnpaidRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicJurorDailyRoute: typeof ApiPublicJurorDailyRoute
  ApiPublicSumupReaderWebhookRoute: typeof ApiPublicSumupReaderWebhookRoute
  ApiPublicSumupWebhookRoute: typeof ApiPublicSumupWebhookRoute
  ApiPublicDeliverooHubIngestRoute: typeof ApiPublicDeliverooHubIngestRoute
  ApiPublicDeliverooPrintBridgeRoute: typeof ApiPublicDeliverooPrintBridgeRoute
  ApiPublicDeliverooWebhookRoute: typeof ApiPublicDeliverooWebhookRoute
  ApiPublicJusteatHubIngestRoute: typeof ApiPublicJusteatHubIngestRoute
  ApiPublicJusteatWebhookRoute: typeof ApiPublicJusteatWebhookRoute
  ApiPublicLandlordReportRoute: typeof ApiPublicLandlordReportRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breakfast-st-albans': {
      id: '/breakfast-st-albans'
      path: '/breakfast-st-albans'
      fullPath: '/breakfast-st-albans'
      preLoaderRoute: typeof BreakfastStAlbansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/court-staff': {
      id: '/court-staff'
      path: '/court-staff'
      fullPath: '/court-staff'
      preLoaderRoute: typeof CourtStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display': {
      id: '/display'
      path: '/display'
      fullPath: '/display'
      preLoaderRoute: typeof DisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-pay-review': {
      id: '/google-pay-review'
      path: '/google-pay-review'
      fullPath: '/google-pay-review'
      preLoaderRoute: typeof GooglePayReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-pay-test': {
      id: '/google-pay-test'
      path: '/google-pay-test'
      fullPath: '/google-pay-test'
      preLoaderRoute: typeof GooglePayTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/halal-food-st-albans': {
      id: '/halal-food-st-albans'
      path: '/halal-food-st-albans'
      fullPath: '/halal-food-st-albans'
      preLoaderRoute: typeof HalalFoodStAlbansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judges': {
      id: '/judges'
      path: '/judges'
      fullPath: '/judges'
      preLoaderRoute: typeof JudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judges-menu': {
      id: '/judges-menu'
      path: '/judges-menu'
      fullPath: '/judges-menu'
      preLoaderRoute: typeof JudgesMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juror': {
      id: '/juror'
      path: '/juror'
      fullPath: '/juror'
      preLoaderRoute: typeof JurorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juror-demo': {
      id: '/juror-demo'
      path: '/juror-demo'
      fullPath: '/juror-demo'
      preLoaderRoute: typeof JurorDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juror-qr': {
      id: '/juror-qr'
      path: '/juror-qr'
      fullPath: '/juror-qr'
      preLoaderRoute: typeof JurorQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jury-menu': {
      id: '/jury-menu'
      path: '/jury-menu'
      fullPath: '/jury-menu'
      preLoaderRoute: typeof JuryMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kds': {
      id: '/kds'
      path: '/kds'
      fullPath: '/kds'
      preLoaderRoute: typeof KdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord': {
      id: '/landlord'
      path: '/landlord'
      fullPath: '/landlord'
      preLoaderRoute: typeof LandlordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lunch-st-albans': {
      id: '/lunch-st-albans'
      path: '/lunch-st-albans'
      fullPath: '/lunch-st-albans'
      preLoaderRoute: typeof LunchStAlbansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-direct': {
      id: '/order-direct'
      path: '/order-direct'
      fullPath: '/order-direct'
      preLoaderRoute: typeof OrderDirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tab': {
      id: '/tab'
      path: '/tab'
      fullPath: '/tab'
      preLoaderRoute: typeof TabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-login': {
      id: '/team-login'
      path: '/team-login'
      fullPath: '/team-login'
      preLoaderRoute: typeof TeamLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/till': {
      id: '/till'
      path: '/till'
      fullPath: '/till'
      preLoaderRoute: typeof TillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watcher-download': {
      id: '/watcher-download'
      path: '/watcher-download'
      fullPath: '/watcher-download'
      preLoaderRoute: typeof WatcherDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/admin/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/admin/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/broadcasts': {
      id: '/admin/broadcasts'
      path: '/admin/broadcasts'
      fullPath: '/admin/broadcasts'
      preLoaderRoute: typeof AdminBroadcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/court-staff': {
      id: '/admin/court-staff'
      path: '/admin/court-staff'
      fullPath: '/admin/court-staff'
      preLoaderRoute: typeof AdminCourtStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customer-discounts': {
      id: '/admin/customer-discounts'
      path: '/admin/customer-discounts'
      fullPath: '/admin/customer-discounts'
      preLoaderRoute: typeof AdminCustomerDiscountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/admin/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/juror-attendance': {
      id: '/admin/juror-attendance'
      path: '/admin/juror-attendance'
      fullPath: '/admin/juror-attendance'
      preLoaderRoute: typeof AdminJurorAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/admin/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/admin/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/operations': {
      id: '/admin/operations'
      path: '/admin/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AdminOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pos': {
      id: '/admin/pos'
      path: '/admin/pos'
      fullPath: '/admin/pos'
      preLoaderRoute: typeof AdminPosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/promos': {
      id: '/admin/promos'
      path: '/admin/promos'
      fullPath: '/admin/promos'
      preLoaderRoute: typeof AdminPromosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff-ops': {
      id: '/admin/staff-ops'
      path: '/admin/staff-ops'
      fullPath: '/admin/staff-ops'
      preLoaderRoute: typeof AdminStaffOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vouchers': {
      id: '/admin/vouchers'
      path: '/admin/vouchers'
      fullPath: '/admin/vouchers'
      preLoaderRoute: typeof AdminVouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderId': {
      id: '/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/order/$orderId'
      preLoaderRoute: typeof OrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$orderId': {
      id: '/pay/$orderId'
      path: '/pay/$orderId'
      fullPath: '/pay/$orderId'
      preLoaderRoute: typeof PayOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$orderId': {
      id: '/print/$orderId'
      path: '/print/$orderId'
      fullPath: '/print/$orderId'
      preLoaderRoute: typeof PrintOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cleanup-unpaid': {
      id: '/api/public/cleanup-unpaid'
      path: '/api/public/cleanup-unpaid'
      fullPath: '/api/public/cleanup-unpaid'
      preLoaderRoute: typeof ApiPublicCleanupUnpaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/juror-daily': {
      id: '/api/public/juror-daily'
      path: '/api/public/juror-daily'
      fullPath: '/api/public/juror-daily'
      preLoaderRoute: typeof ApiPublicJurorDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sumup-reader-webhook': {
      id: '/api/public/sumup-reader-webhook'
      path: '/api/public/sumup-reader-webhook'
      fullPath: '/api/public/sumup-reader-webhook'
      preLoaderRoute: typeof ApiPublicSumupReaderWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sumup-webhook': {
      id: '/api/public/sumup-webhook'
      path: '/api/public/sumup-webhook'
      fullPath: '/api/public/sumup-webhook'
      preLoaderRoute: typeof ApiPublicSumupWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/deliveroo/hub-ingest': {
      id: '/api/public/deliveroo/hub-ingest'
      path: '/api/public/deliveroo/hub-ingest'
      fullPath: '/api/public/deliveroo/hub-ingest'
      preLoaderRoute: typeof ApiPublicDeliverooHubIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/deliveroo/print-bridge': {
      id: '/api/public/deliveroo/print-bridge'
      path: '/api/public/deliveroo/print-bridge'
      fullPath: '/api/public/deliveroo/print-bridge'
      preLoaderRoute: typeof ApiPublicDeliverooPrintBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/deliveroo/webhook': {
      id: '/api/public/deliveroo/webhook'
      path: '/api/public/deliveroo/webhook'
      fullPath: '/api/public/deliveroo/webhook'
      preLoaderRoute: typeof ApiPublicDeliverooWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/justeat/hub-ingest': {
      id: '/api/public/justeat/hub-ingest'
      path: '/api/public/justeat/hub-ingest'
      fullPath: '/api/public/justeat/hub-ingest'
      preLoaderRoute: typeof ApiPublicJusteatHubIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/justeat/webhook': {
      id: '/api/public/justeat/webhook'
      path: '/api/public/justeat/webhook'
      fullPath: '/api/public/justeat/webhook'
      preLoaderRoute: typeof ApiPublicJusteatWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/landlord/report': {
      id: '/api/public/landlord/report'
      path: '/api/public/landlord/report'
      fullPath: '/api/public/landlord/report'
      preLoaderRoute: typeof ApiPublicLandlordReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  BreakfastStAlbansRoute: BreakfastStAlbansRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ComplaintsRoute: ComplaintsRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  CourtStaffRoute: CourtStaffRoute,
  DisplayRoute: DisplayRoute,
  DriverRoute: DriverRoute,
  FaqRoute: FaqRoute,
  GdprRoute: GdprRoute,
  GooglePayReviewRoute: GooglePayReviewRoute,
  GooglePayTestRoute: GooglePayTestRoute,
  HalalFoodStAlbansRoute: HalalFoodStAlbansRoute,
  JudgesRoute: JudgesRoute,
  JudgesMenuRoute: JudgesMenuRoute,
  JurorRoute: JurorRoute,
  JurorDemoRoute: JurorDemoRoute,
  JurorQrRoute: JurorQrRoute,
  JuryMenuRoute: JuryMenuRoute,
  KdsRoute: KdsRoute,
  LandlordRoute: LandlordRoute,
  LunchStAlbansRoute: LunchStAlbansRoute,
  MenuRoute: MenuRoute,
  OrderDirectRoute: OrderDirectRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StaffRoute: StaffRoute,
  TabRoute: TabRoute,
  TeamLoginRoute: TeamLoginRoute,
  TermsRoute: TermsRoute,
  TillRoute: TillRoute,
  WatcherDownloadRoute: WatcherDownloadRoute,
  AdminAccountsRoute: AdminAccountsRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminBroadcastsRoute: AdminBroadcastsRoute,
  AdminCourtStaffRoute: AdminCourtStaffRoute,
  AdminCustomerDiscountsRoute: AdminCustomerDiscountsRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminJurorAttendanceRoute: AdminJurorAttendanceRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminOperationsRoute: AdminOperationsRoute,
  AdminPosRoute: AdminPosRoute,
  AdminPromosRoute: AdminPromosRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffOpsRoute: AdminStaffOpsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVouchersRoute: AdminVouchersRoute,
  BlogSlugRoute: BlogSlugRoute,
  OrderOrderIdRoute: OrderOrderIdRoute,
  PayOrderIdRoute: PayOrderIdRoute,
  PrintOrderIdRoute: PrintOrderIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicCleanupUnpaidRoute: ApiPublicCleanupUnpaidRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicJurorDailyRoute: ApiPublicJurorDailyRoute,
  ApiPublicSumupReaderWebhookRoute: ApiPublicSumupReaderWebhookRoute,
  ApiPublicSumupWebhookRoute: ApiPublicSumupWebhookRoute,
  ApiPublicDeliverooHubIngestRoute: ApiPublicDeliverooHubIngestRoute,
  ApiPublicDeliverooPrintBridgeRoute: ApiPublicDeliverooPrintBridgeRoute,
  ApiPublicDeliverooWebhookRoute: ApiPublicDeliverooWebhookRoute,
  ApiPublicJusteatHubIngestRoute: ApiPublicJusteatHubIngestRoute,
  ApiPublicJusteatWebhookRoute: ApiPublicJusteatWebhookRoute,
  ApiPublicLandlordReportRoute: ApiPublicLandlordReportRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
